version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      patch-and-minor:
        update-types:
          - patch
          - minor
      types:
        patterns:
          - "@types/*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: build
